name: Test
on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start PostgreSQL
        run: docker run --name postgres -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 postgres:13

      - name: Install dependencies
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/chessmong
        run: |
          npm install
          npx prisma db push
          npx prisma generate

      - name: Run tests
        env:
          CODE: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/chessmong
          JWT_SECRET: test
          JWT_EXPIRES_IN: 1d
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          npm run test:e2e
